# Generated by Django 2.0.3 on 2018-03-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lon',
            field=models.CharField(max_length=20),
        ),
    ]
