# Generated by Django 2.0.3 on 2018-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='latin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
