# Generated by Django 2.0.3 on 2018-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bird_latin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
