# Generated by Django 2.0.3 on 2018-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180603_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bird_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='latin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
