# Generated by Django 2.0.3 on 2019-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180619_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwsid', models.CharField(max_length=200)),
                ('violation_id', models.CharField(max_length=200)),
            ],
        ),
    ]
