# Generated by Django 2.0.3 on 2019-01-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='compl_per_begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='is_health_based',
            field=models.BooleanField(default=False),
        ),
    ]
