# Generated by Django 2.0.3 on 2019-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190105_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='is_health_based',
        ),
        migrations.AddField(
            model_name='violation',
            name='is_health_based_ind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
